from ClientAlreadyExistsException import ClientAlreadyExistsException
from .ClientDoesntHaveCNPJException import ClientDoesntHaveCNPJException
from .ClientDoesntHaveCPFException import ClientDoesntHaveCPFException
from .ClientBranchDoesntExistException import BranchDoesntExistException